### ISSUE TITLE
Auto-verify an email for its first session?

### ISSUE THREAD

**Issue by jankeromnes** [espadrine/email-login#1]
In my login system, if an email is not known already, a new user is created. Since no private data can be accessed that way, I don't mind if that email isn't verified the first time.

Is there a way, for the current session, to say an email is verified even if there was no proof?

**Comment by espadrine** [comment]
`session.emailVerified()` only gives information about whether the email was verified, not that the user coming from that email address is authenticated. Knowing that the email was verified requires proof.

However, authenticating requires a different proof, which is contained in the cookie. That authentication guarantees that whoever knocks on your door again was the same person that knocked before. We don't know what their email address is, but we know they're the same person. You can rely on that.

I would be careful, though: if A (good) and B (evil) are people and @A and @B are email addresses, we can have the following hack:
1. B logs in as @A, knowing that A did not sign up for the service yet, but plans to.
2. A logs in as @A, getting a shared account with B unknowingly.
3. B can access everything that A can access.

**Comment by jankeromnes** [comment]
Right, that scenario would be problematic. One would need to refuse concurrent sessions associated to the same email, or visibly show something like "someone else is currently logged-in [log them out]".

**Comment by jankeromnes** [comment]
> `session.emailVerified()` only gives information about whether the email was verified, not that the user coming from that email address is authenticated.

Well, if you have access to a `session` object at all, that means that the user's token has been authenticated to that session, right? I thought there were no unauthenticated sessions.

**Comment by espadrine** [comment]
> One would need to refuse concurrent sessions associated to the same email, or visibly show something like "someone else is currently logged-in [log them out]".

Currently, we can only logout() people from their cookie token, which only they know. I'll add two API functions, one to get all session ids from an email address (say, `account(email, cb)`), and one to logout from a session id (say, `remoteLogout(sessionId, cb)`).

> Well, if you have access to a session object at all, that means that the user's token has been authenticated to that session, right? I thought there were no unauthenticated sessions.

That session is authenticated, yes, but we have no idea whether the person that created that session owns access to the associated email address (if there is one), unless `session.emailVerified()` is true.

**Comment by jankeromnes** [comment]
- +1 for `account(email, callback)`, but why only return session ids? Why not complete `session` objects?
- `remoteLogout(sessionId, callback)` is strange, because you could be not remote. What about `session.destroy()`?

Example code with both of my suggestions:

```
emailLogin.account(email, function (err, sessions) {
  sessions.forEach(function (session) {
    if (session.id !== localSessionId) session.destroy();
  });
});
```

**Comment by jankeromnes** [comment]
(Actually, I think that `account(email, callback)` should return not only all the sessions, but also the "information associated to an email address" mentioned in the README).

**Comment by espadrine** [comment]
> +1 for account(email, callback), but why only return session ids? Why not complete session objects?

Good point.

> remoteLogout(sessionId, callback) is strange, because you could be not remote. What about session.destroy()?

If you were not remote, you would use `logout(cookieToken, cb)`.

Additionally, Session is agnostic to the storage primitives, which would be useful ultimately

**Comment by espadrine** [comment]
From an outside discussion, it seemed we'd have:
- `deleteSession(sessionId, cb)`
- `account(email, cb)`, with the callback returning an Account object:
  - email
  - sessionIds (list of session Ids corresponding to all sessions for which ownership of the email address was proved)

**Comment by jankeromnes** [comment]
I'd prefer that `account(email, cb)` calls back with a complete list of `session` objects rather than IDs:

```
account: {
  email: 'xxx@yyy.zzz',
  sessions: [ /* all the user's sessions */ ]
}
```

I believe I/O will not be an issue, because `account(email, cb)` will be called occasionally, and an account will usually have a limited number of sessions.
