### ISSUE TITLE
Any advisory on upgrading from 1.0.1 to 1.1.0?

### ISSUE THREAD

**Issue by jankeromnes** [espadrine/email-login#7]
I notice that `email-login` may have started to use PostgreSQL, and also switched to 128-bit token IDs. Is it safe to upgrade? Should I nuke the `./tokens/` folder?

**Comment by espadrine** [comment]
It should be safe to upgrade without change, although I advise you to make a local copy of your production server and test it to verify that it won't break.

The default is still to use the file system as a backing store; the use of a PostgreSQL wire-compatible database format (such as CockroachDB and… well… PostgreSQL) is optional.

**Comment by jankeromnes** [comment]
Upgrading actually fixed my Travis CI build! 🎉 Thanks! 😄

See also: https://github.com/JanitorTechnology/janitor/pull/102
